Asm
FMyb/first-term pull request #2
Opened 2020-06-30 12:08 UTC by FMyb

2020-06-30 14:15 UTC, kt-cpp requested changes
Напиши контракты ко всем своим функциям, без них невозможно нормально проверят

2020-06-30 15:10 UTC, FMyb commented
> Напиши контракты ко всем своим функциям, без них невозможно нормально проверять

fixed

2020-06-30 16:53 UTC, kt-cpp requested changes
В целом норм, но опять код работающий благодаря чуду)

2020-06-30 16:53 UTC, kt-cpp commented on asm/mul.asm
> +                call            mul_long_short_for_mul_long_long
Функция ожидает длину в `rcx`, перед вызовом не вижу с ним никаких операций, судя по контракту длина передаётся в `r10`

2020-06-30 16:53 UTC, kt-cpp commented on asm/mul.asm
> +                call            add_long_long_for_mul_long_long
Функция ожидает длину в `rcx`, перед вызовом не вижу с ним никаких операций, судя по контракту длина передаётся в `r10`

2020-06-30 16:53 UTC, kt-cpp commented on asm/mul.asm
> +;    sum is written to r8
Стоит упомянуть в контракте, что длина результат на 1 превосходит длину операндов, ибо описание контракта совпадает с контрактом функции Сорокина, где это не так

2020-06-30 16:53 UTC, kt-cpp commented on asm/mul.asm
> +;    product is written to r9
Аналогично тут, стоит упомянуть что в ответ пишется полный результат умножения, которые потенциально длиннее длинного числа, ибо описание контракта совпадает с контрактом функции Сорокина, где это не так

2020-07-01 07:06 UTC, FMyb commented on asm/mul.asm
> +                call            add_long_long_for_mul_long_long
fixed

2020-07-01 07:06 UTC, FMyb commented on asm/mul.asm
> +;    sum is written to r8
fixed

2020-07-01 07:08 UTC, FMyb commented on asm/mul.asm
> +;    product is written to r9
fixed

2020-07-01 12:28 UTC, kt-cpp requested changes

2020-07-01 12:28 UTC, kt-cpp commented on asm/sub.asm
> +                mov             rsi, r8
Ты меняешь числа местами, ломая этим контракт. Для внешнего наблюдателя будет выглядеть, словно ты из `rsi` вычел `rdi`

2020-07-01 12:28 UTC, kt-cpp commented on asm/mul.asm
> +;    product is written to r9 (full answer, can be longer than long number)
[minor] Длиннее на сколько,

2020-07-02 08:17 UTC, FMyb commented on asm/sub.asm
> +                mov             rsi, r8
fixed

2020-07-02 08:22 UTC, FMyb commented on asm/mul.asm
> +;    product is written to r9 (full answer, can be longer than long number)
fixed

2020-07-06 10:06 UTC, kt-cpp commented on asm/mul.asm
> +                sub             rsp, 4 * 128 * 8 + 129 * 8
Выдели 129 * 8 в `mul_long_long` так как эта память не используется в `main`

2020-07-06 10:09 UTC, kt-cpp commented on asm/mul.asm
> +                ret
Объединить эти две функции в одну

2020-07-06 10:10 UTC, kt-cpp commented on asm/mul.asm
> +                ret
Докажи, что такая функция тебе нужна, если ты прибавляешь к 256р числу 129 разрядные числа по смещению

2020-07-06 10:11 UTC, kt-cpp requested changes
Пофиксить копипасту, выделить доп память в функции, разобраться с еще одной функцией

2020-07-06 10:41 UTC, FMyb commented on asm/mul.asm
> +                sub             rsp, 4 * 128 * 8 + 129 * 8
fixed

2020-07-06 12:28 UTC, FMyb commented on asm/mul.asm
> +                ret
fixed

2020-07-06 12:39 UTC, FMyb commented on asm/mul.asm
> +                ret
Не совсем понял что Вы просите доказать, можете пожалуйста пояснить?

2020-07-06 15:36 UTC, FMyb commented on asm/mul.asm
> +                ret
Не совсем понял что Вы имели ввиду. Можете, пожалуйста, пояснить что мне нужно доказать?

2021-06-05 16:24 UTC, merged