Bigint
FMyb/first-term pull request #3
Opened 2020-06-30 12:31 UTC by FMyb

2020-07-02 01:03 UTC, kt-cpp requested changes
Комментарии помеченные [note] не обязательны к исправлению

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.h
>      ~big_integer();
[semantic] Если уж конструктор копирования дефолтный, то почему деструктор не такой?

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    sign = value >= 0 ? 1 : -1;
[semantic] Лучше использовать member initializer list

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    val.clear(); // TODO
[style] TODO

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    *this = big_integer(0);
[semantic] Лучше явно звать дефолтный конструктор перед выполнением конструктора копирования

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (str[0] == '-') {
[semantic, minor] Не рассмотрены случаи префиксного `+` и символов, которые не являются цифрами.

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        *this *= 10;
[guarantees] Здесь и далее начинаются проблемы с исключениями. Постарайся добиться, чтобы каждый метод реализовывал наилучшую из возможных для него гарантий.

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    big_integer tmp(other);
[performance, minor] Излишняя работа если `&other == this`

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        long long cur = 0;
[style] `long long` не является типом фиксированной длины

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            cur = sum / (1LL << 32);
[style, minor] Компилятор всё равно это сделает за тебя, но лучше использовать сдвиги вместо явного деления

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            res.val[i] = static_cast<uint32_t>(sum % (1LL << 32));
[semantic] `static_cast` уже берёт младшие биты, во взятии остатка нет нужды
Это не единственное место с подобной проблемой

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        res.shrink_to_fit();
[style, minor] Количество вызовов `shrink_to_fit` может быть уменьшено

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            *this = -(other - *this);
[performance] Унарный минус -- это дорогая операция, можно сделать это действие оптимальнее

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        long long b = 0;
[style, note] `b` можно создать позже, тогда, когда она понадобится

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +                val.push_back(0);
[performance] Можно учесть разницу в размерах и избежать переаллокаций из-за последовательных `push_back`

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (*this == 0 || other == 0) *this = 0;
[style] тело `if` лучше окружать фигурными скобками, поможет избежать ошибок в будущем

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    *this = *this << value;
[semantic] Часть бинарных операций определена через версию с присваиванием, а часть -- наоборот.

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return std::min(static_cast<uint32_t>(t1 / t2), UINT32_MAX);
[style, minor] `UINT32_MAX` лучше сделать статической переменной

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer div_bi_short(big_integer &a, uint32_t b) {
[guarantees] Что произойдёт в случае если `b == 0`?

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        ans.val.push_back(static_cast<uint32_t>((temp / b)));
[performance] Можно избежать переаллокаций от последовательных `push_back`

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (a < b) {
[performance] Эта проверка может быть совершена ранее, чтобы избежать ненужных аллокаций

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +uint32_t b_and(uint32_t a, uint32_t b) {
[note] Эти конструкции удобно выразить через лямбда-выражения

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    big_integer y = b;
[performance] Иногда возможно обойтись без копирования `a` и `b`

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        ans = -ans;
[performance] Унарный минус -- дорогая операция

2020-07-02 01:03 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    for (int i = 0; i < value / 32 && a.size(); i++) {
[style] Лучше явно писать все предикаты, то есть понятнее выглядело бы `a.size() != 0`

2020-07-02 06:31 UTC, FMyb commented on bigint/big_integer.cpp
> +    sign = value >= 0 ? 1 : -1;
fixed

2020-07-02 06:31 UTC, FMyb commented on bigint/big_integer.h
>      ~big_integer();
fixed

2020-07-02 06:31 UTC, FMyb commented on bigint/big_integer.cpp
> +    val.clear(); // TODO
fixed

2020-07-02 06:35 UTC, FMyb commented on bigint/big_integer.cpp
> +    *this = big_integer(0);
fixed

2020-07-02 07:15 UTC, FMyb commented on bigint/big_integer.cpp
> +        ans = -ans;
fixed

2020-07-02 07:15 UTC, FMyb commented on bigint/big_integer.cpp
> +    big_integer y = b;
fixed

2020-07-02 07:15 UTC, FMyb commented on bigint/big_integer.cpp
> +    if (str[0] == '-') {
fixed

2020-07-02 07:43 UTC, FMyb commented on bigint/big_integer.cpp
> +    if (a < b) {
fixed

2020-07-02 07:45 UTC, FMyb commented on bigint/big_integer.cpp
> +    for (int i = 0; i < value / 32 && a.size(); i++) {
fixed

2020-07-02 11:22 UTC, kt-cpp requested changes

2020-07-02 11:22 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    sign = value >= 0 ? 1 : -1;
Не совсем. Поля можно инициализировать сразу перед выполнением тела конструктора. Ниже похожие проблемы.
https://en.cppreference.com/w/cpp/language/constructor

2020-07-02 11:22 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    *this = big_integer();
[minor] Используя синтаксис, похожий на member initialization list можно вызывать другой конструктор до выполнения тела исходного конструктора

2020-07-02 11:22 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (str[0] == '-') {
А если строчка пустая?

2020-07-02 11:22 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            throw;
[semantic] Что кидаем-то?

2020-07-02 12:01 UTC, FMyb commented on bigint/big_integer.cpp
> +    if (str[0] == '-') {
fixed

2020-07-02 12:01 UTC, FMyb commented on bigint/big_integer.cpp
> +    sign = value >= 0 ? 1 : -1;
fixed

2020-07-02 12:01 UTC, FMyb commented on bigint/big_integer.cpp
> +    *this = big_integer();
fixed

2020-07-02 12:01 UTC, FMyb commented on bigint/big_integer.cpp
> +            throw;
fixed

2020-07-02 15:23 UTC, kt-cpp commented
В ревью ещё много неисправленных комментариев, пожалуйста, почини их перед отправкой заявки на проверку.

Их можно увидеть здесь
![image](https://user-images.githubusercontent.com/67123994/86377338-e5817300-bc90-11ea-8a1f-d63b8670b8b6.png)

2020-07-02 17:23 UTC, FMyb commented on bigint/big_integer.cpp
> +            cur = sum / (1LL << 32);
fixed

2020-07-02 17:23 UTC, FMyb commented on bigint/big_integer.cpp
> +        long long cur = 0;
fixed

2020-07-02 17:23 UTC, FMyb commented on bigint/big_integer.cpp
> +    big_integer tmp(other);
fixed

2020-07-02 17:26 UTC, FMyb commented on bigint/big_integer.cpp
> +            res.val[i] = static_cast<uint32_t>(sum % (1LL << 32));
fixed

2020-07-02 17:29 UTC, FMyb commented on bigint/big_integer.cpp
> +        res.shrink_to_fit();
fixed

2020-07-02 17:30 UTC, FMyb commented on bigint/big_integer.cpp
> +            *this = -(other - *this);
fixed

2020-07-02 17:34 UTC, FMyb commented on bigint/big_integer.cpp
> +        long long b = 0;
fixed

2020-07-02 17:35 UTC, FMyb commented on bigint/big_integer.cpp
> +    if (*this == 0 || other == 0) *this = 0;
fixed

2020-07-02 17:39 UTC, FMyb commented on bigint/big_integer.cpp
> +big_integer div_bi_short(big_integer &a, uint32_t b) {
fixed

2020-07-02 17:44 UTC, FMyb commented on bigint/big_integer.cpp
> +    return std::min(static_cast<uint32_t>(t1 / t2), UINT32_MAX);
не очень понял что вы здесь подразумевали

2020-07-02 18:08 UTC, FMyb commented on bigint/big_integer.cpp
> +    *this = *this << value;
fixed

2020-07-02 18:18 UTC, FMyb commented on bigint/big_integer.cpp
> +                val.push_back(0);
fixed

2020-07-02 18:20 UTC, FMyb commented on bigint/big_integer.cpp
> +        ans.val.push_back(static_cast<uint32_t>((temp / b)));
fixed

2020-07-02 18:20 UTC, FMyb commented on bigint/big_integer.cpp
> +        *this *= 10;
Можете пояснить что конкретно здесь не так?

2020-07-02 18:21 UTC, FMyb commented
Прошу прощения, не обратил внимания на эту кнопку.

2020-07-03 04:14 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    sign = value >= 0 ? 1 : -1;
Строчки 25 и 26 можно тоже так записать

2020-07-03 04:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return std::min(static_cast<uint32_t>(t1 / t2), UINT32_MAX);
Я считаю, что `UINT32_MAX` это в какой-то степени магическое число, и его стоит делать `static` полем структуры или `static` глобальной переменной, предварительно дав осмысленное имя (конкретно эту константу я бы назвал как-нибудь вроде MAX_DIGIT). Такое в целом нужно делать для всяких значений типа 64 и 32 двумя строчками выше, чтобы при прочтении фокусироваться на смысле констант, а не их фактическом значении. 
Кстати, сейчас обратил внимание, а зачем нужен минимум?

2020-07-03 04:58 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        *this *= 10;
Не могу, потому что всё хорошо. Кажется, я что-то перепутал, когда оставлял комментарий.
Извини.

2020-07-03 07:28 UTC, FMyb commented on bigint/big_integer.cpp
> +    sign = value >= 0 ? 1 : -1;
fixed

2020-07-03 07:35 UTC, FMyb commented on bigint/big_integer.cpp
> +    return std::min(static_cast<uint32_t>(t1 / t2), UINT32_MAX);
Кстати действительно не нужен, было в статье про деление, по этому и написал. fixed.

2020-07-03 11:26 UTC, kt-cpp approved these changes

2020-07-03 11:26 UTC, merged