Bigint-opt
FMyb/first-term pull request #4
Opened 2020-07-02 12:13 UTC by FMyb

2020-07-03 14:51 UTC, kt-cpp requested changes

2020-07-03 14:51 UTC, kt-cpp commented on bigint-optimized/uint_vector.h
> +            }
[minor] Для `uint32_t` это бессмысленно, в случае small можно вообще ничего не делать

2020-07-03 14:51 UTC, kt-cpp commented on bigint-optimized/uint_vector.h
> +            }
Такое есть в нескольких местах

2020-07-03 14:51 UTC, kt-cpp commented on bigint-optimized/uint_vector.h
> +                tmp.push_back(x);
[minor] У вектора есть конструктор от двух итераторов, чтобы такое руками не делать

2020-07-03 14:51 UTC, kt-cpp commented on bigint-optimized/uint_vector.h
> +                std::copy_n(tmp.begin(), size_, static_data);
При SO нет смысла сжиматься. Дорога не абстрактная динамическая память, а её аллокация. Если она у тебя уже есть нет смысл её отпускать.
Правда у тебя от этого отвалится часть код, например, сравнение. Будь аккуратнее при исправлениях

2020-07-03 14:51 UTC, kt-cpp commented on bigint-optimized/uint_vector.h
> +            std::reverse(dynamic_data->data.begin(), dynamic_data->data.end());
Почему нет `unshare`? Это же мутабельная операция

2020-07-03 14:51 UTC, kt-cpp commented on bigint-optimized/uint_vector.h
> +    }
Можно делать и inplace, избежав лишних копирований

2020-07-03 14:51 UTC, kt-cpp commented on bigint-optimized/uint_vector.h
> +    }
[note] Обычно реализовывают `=` черещ свап, когда есть только копирования. У тебя получается больше копий чем можно, реализовывая свап руками особенно в случае двух уникальный big

2020-07-03 14:51 UTC, kt-cpp commented on bigint-optimized/uint_vector.h
> +    static size_t const MAX_STATIC_SIZE = sizeof(dynamic_buffer);
Тут очень странный `sizeof`, учитывая что ты хранишь `dynamic_buffer *`, так ещё нигде не учтён размер `uint32_t`

2020-07-03 14:51 UTC, kt-cpp commented on bigint-optimized/uint_vector.h
> +    static size_t const MAX_STATIC_SIZE = sizeof(dynamic_buffer);
[minor] `constexpr`

2020-07-03 16:05 UTC, FMyb commented on bigint-optimized/uint_vector.h
> +            }
fixed

2020-07-03 16:06 UTC, FMyb commented on bigint-optimized/uint_vector.h
> +                tmp.push_back(x);
fixed

2020-07-03 16:07 UTC, FMyb commented on bigint-optimized/uint_vector.h
> +            std::reverse(dynamic_data->data.begin(), dynamic_data->data.end());
fixed

2020-07-03 16:17 UTC, FMyb commented on bigint-optimized/uint_vector.h
> +                std::copy_n(tmp.begin(), size_, static_data);
fixed

2020-07-03 16:28 UTC, FMyb commented on bigint-optimized/uint_vector.h
> +    static size_t const MAX_STATIC_SIZE = sizeof(dynamic_buffer);
fixed

2020-07-03 16:35 UTC, FMyb commented on bigint-optimized/uint_vector.h
> +    }
fixed

2020-07-07 18:51 UTC, kt-cpp commented on bigint-optimized/uint_vector.h
> +            }
вижу: if (is_small()) static_data[--size_].~uint32_t(); . достаточно --size

2020-07-07 18:59 UTC, FMyb commented on bigint-optimized/uint_vector.h
> +            }
fixed

2020-07-07 19:43 UTC, kt-cpp requested changes

2020-07-07 19:43 UTC, kt-cpp commented on bigint-optimized/uint_vector.h
> +        this->~uint_vector();
так не надо

2020-07-07 19:48 UTC, FMyb commented on bigint-optimized/uint_vector.h
> +        this->~uint_vector();
fixed

2020-07-07 19:59 UTC, merged